// Generated by OASmith. Do not edit.
import 'dart:convert';

import 'package:http/http.dart' as http;

import 'models.dart';
export 'models.dart';

class ApiStatusException implements Exception {
  const ApiStatusException(this.statusCode);
  final int statusCode;
  @override
  String toString() => 'API returned HTTP $statusCode';
}

class PublicApiClient {
  PublicApiClient({
    required this.baseUri,
    required this.send,
    this.responseError,
    this.readBody,
  });
  final Uri baseUri;
  final Future<http.StreamedResponse> Function(http.BaseRequest) send;
  final Future<Exception> Function(http.StreamedResponse)? responseError;
  final Future<List<int>> Function(http.StreamedResponse, int)? readBody;

  Uri _uri(String path, Map<String, dynamic> query) {
    if (!path.startsWith('/') || path.startsWith('//'))
      throw const FormatException('API path must be absolute');
    final uri = baseUri
        .resolve(path)
        .replace(queryParameters: query.isEmpty ? null : query);
    if (uri.origin != baseUri.origin)
      throw const FormatException('API path escapes configured origin');
    return uri;
  }

  String _wire(Object? value) {
    final encoded = encodePublicJson(value);
    if (encoded is String) return encoded;
    if (encoded is num || encoded is bool) return encoded.toString();
    throw const FormatException('API parameter must be scalar');
  }

  Future<Exception> _error(http.StreamedResponse response) async =>
      responseError == null
      ? ApiStatusException(response.statusCode)
      : responseError!(response);
  Future<List<int>> _readBounded(http.StreamedResponse response) async {
    if (readBody != null) return readBody!(response, 4 << 20);
    final bytes = <int>[];
    await for (final chunk in response.stream) {
      if (bytes.length + chunk.length > (4 << 20))
        throw const FormatException('API response exceeds 4 MiB');
      bytes.addAll(chunk);
    }
    return bytes;
  }

  Future<OpenAPIJSONDocument> openapi() async {
    final query = <String, dynamic>{};
    final request = http.Request("GET", _uri('/', query));
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return decodeOpenAPIJSONDocument(jsonDecode(utf8.decode(bytes)));
  }

  Future<void> headOpenapi() async {
    final query = <String, dynamic>{};
    final request = http.Request("HEAD", _uri('/', query));
    request.headers['Accept'] = "*/*";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<CreatedCLIAuthorization> createCLIAuthorization({
    required CreateCLIAuthorization body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request("POST", _uri('/cli/authorizations', query));
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return CreatedCLIAuthorization.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<http.StreamedResponse> cliAuthorizationEvents({
    required CLIAuthorizationCode code,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "GET",
      _uri(
        '/cli/authorizations/${Uri.encodeComponent(_wire(code))}/events',
        query,
      ),
    );
    request.headers['Accept'] = "text/event-stream";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    return response;
  }

  Future<http.StreamedResponse> episodeDeletionEvents({
    required EpisodeDeletionRunID episodeDeletionRunId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "GET",
      _uri(
        '/s/episode-deletions/${Uri.encodeComponent(_wire(episodeDeletionRunId))}/events',
        query,
      ),
    );
    request.headers['Accept'] = "text/event-stream";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    return response;
  }

  Future<EpisodePackage> createEpisodePackage({
    required CreateEpisodePackage body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request("POST", _uri('/s/episode-packages', query));
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return EpisodePackage.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<void> cancelEpisodePackage({
    required UploadSessionID uploadSessionId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "DELETE",
      _uri(
        '/s/episode-packages/${Uri.encodeComponent(_wire(uploadSessionId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<EpisodePackage> completeEpisodePackage({
    required UploadSessionID uploadSessionId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri(
        '/s/episode-packages/${Uri.encodeComponent(_wire(uploadSessionId))}/complete',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return EpisodePackage.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<PresignedEpisodeUploadParts> presignEpisodePackageParts({
    required UploadSessionID uploadSessionId,
    required int objectIndex,
    required PresignEpisodeUploadSessionParts body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri(
        '/s/episode-packages/${Uri.encodeComponent(_wire(uploadSessionId))}/objects/${Uri.encodeComponent(_wire(objectIndex))}/parts',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return PresignedEpisodeUploadParts.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<EpisodeUploadSession> createEpisodeUploadSession({
    required CreateEpisodeUploadSession body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri('/s/episode-upload-sessions', query),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{200, 201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return EpisodeUploadSession.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<EpisodeUploadSession> getEpisodeUploadSession({
    required UploadSessionID uploadSessionId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "GET",
      _uri(
        '/s/episode-upload-sessions/${Uri.encodeComponent(_wire(uploadSessionId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return EpisodeUploadSession.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<EpisodeUploadSession> updateEpisodeUploadSession({
    required UploadSessionID uploadSessionId,
    required PatchEpisodeUploadSession body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "PUT",
      _uri(
        '/s/episode-upload-sessions/${Uri.encodeComponent(_wire(uploadSessionId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return EpisodeUploadSession.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<void> cancelEpisodeUploadSession({
    required UploadSessionID uploadSessionId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "DELETE",
      _uri(
        '/s/episode-upload-sessions/${Uri.encodeComponent(_wire(uploadSessionId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<Episode> completeEpisodeUploadSession({
    required UploadSessionID uploadSessionId,
    required CompleteEpisodeUploadSession body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri(
        '/s/episode-upload-sessions/${Uri.encodeComponent(_wire(uploadSessionId))}/complete',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{200, 201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return Episode.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<http.StreamedResponse> episodeUploadSessionEvents({
    required UploadSessionID uploadSessionId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "GET",
      _uri(
        '/s/episode-upload-sessions/${Uri.encodeComponent(_wire(uploadSessionId))}/events',
        query,
      ),
    );
    request.headers['Accept'] = "text/event-stream";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    return response;
  }

  Future<PresignedEpisodeUploadParts> presignEpisodeUploadSessionParts({
    required UploadSessionID uploadSessionId,
    required PresignEpisodeUploadSessionParts body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri(
        '/s/episode-upload-sessions/${Uri.encodeComponent(_wire(uploadSessionId))}/parts/presign',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return PresignedEpisodeUploadParts.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<CreatedPublicEpisodeDeletion> createEpisodeDeletion({
    required EpisodeID episodeId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri(
        '/s/episodes/${Uri.encodeComponent(_wire(episodeId))}/deletions',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{202}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return CreatedPublicEpisodeDeletion.fromJson(
      jsonDecode(utf8.decode(bytes)),
    );
  }

  Future<CreatedImageUploadPresign> createImageUploadPresign({
    required CreateImageUploadPresign body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri('/s/image-uploads/presign', query),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return CreatedImageUploadPresign.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<ImageAsset> completeImageUpload({
    required ImageAssetID imageAssetId,
    required CompleteImageUpload body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri(
        '/s/image-uploads/${Uri.encodeComponent(_wire(imageAssetId))}/complete',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return ImageAsset.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<ImportCapacity> getImportCapacity() async {
    final query = <String, dynamic>{};
    final request = http.Request("GET", _uri('/s/import-capacity', query));
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return ImportCapacity.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<CreatedPublicRSSImport> importRSS({
    required ImportRSSRequest body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request("POST", _uri('/s/rss-imports', query));
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{202}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return CreatedPublicRSSImport.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<http.StreamedResponse> importRSSRunEvents({
    required ImportRunID importRunId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "GET",
      _uri(
        '/s/rss-imports/${Uri.encodeComponent(_wire(importRunId))}/events',
        query,
      ),
    );
    request.headers['Accept'] = "text/event-stream";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    return response;
  }

  Future<http.StreamedResponse> showDeletionEvents({
    required ShowDeletionRunID showDeletionRunId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "GET",
      _uri(
        '/s/show-deletions/${Uri.encodeComponent(_wire(showDeletionRunId))}/events',
        query,
      ),
    );
    request.headers['Accept'] = "text/event-stream";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    return response;
  }

  Future<List<Show>> listShows() async {
    final query = <String, dynamic>{};
    final request = http.Request("GET", _uri('/s/shows', query));
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return expectPublicList(jsonDecode(utf8.decode(bytes)))
        .map((item) => Show.fromJson(item))
        .toList();
  }

  Future<Show> createShow({required CreateShow body}) async {
    final query = <String, dynamic>{};
    final request = http.Request("POST", _uri('/s/shows', query));
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return Show.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<CreatedPublicShowDeletion> createShowDeletion({
    required ShowSlug showSlug,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri('/s/shows/${Uri.encodeComponent(_wire(showSlug))}/deletions', query),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{202}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return CreatedPublicShowDeletion.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<EpisodeOrder> getEpisodeOrder({required ShowSlug showSlug}) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "GET",
      _uri(
        '/s/shows/${Uri.encodeComponent(_wire(showSlug))}/episode-order',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return EpisodeOrder.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<EpisodeOrder> setEpisodeOrder({
    required ShowSlug showSlug,
    required SetEpisodeOrder body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "PUT",
      _uri(
        '/s/shows/${Uri.encodeComponent(_wire(showSlug))}/episode-order',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return EpisodeOrder.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<EpisodePage> listEpisodes({
    required ShowSlug showSlug,
    EpisodePageLimit? limit,
    EpisodePageCursor? cursor,
  }) async {
    final query = <String, dynamic>{};
    if (limit != null) query["limit"] = _wire(limit);
    if (cursor != null) query["cursor"] = _wire(cursor);
    final request = http.Request(
      "GET",
      _uri('/s/shows/${Uri.encodeComponent(_wire(showSlug))}/episodes', query),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return EpisodePage.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<PendingShowInvitation> createShowInvitation({
    required ShowSlug showSlug,
    required CreateShowInvitation body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri(
        '/s/shows/${Uri.encodeComponent(_wire(showSlug))}/invitations',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return PendingShowInvitation.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<PendingShowInvitation> updateShowInvitationRole({
    required ShowSlug showSlug,
    required ShowInvitationID invitationId,
    required UpdateShowMemberRole body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "PUT",
      _uri(
        '/s/shows/${Uri.encodeComponent(_wire(showSlug))}/invitations/${Uri.encodeComponent(_wire(invitationId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return PendingShowInvitation.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<void> revokeShowInvitation({
    required ShowSlug showSlug,
    required ShowInvitationID invitationId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "DELETE",
      _uri(
        '/s/shows/${Uri.encodeComponent(_wire(showSlug))}/invitations/${Uri.encodeComponent(_wire(invitationId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<ShowMemberCollection> listShowMembers({
    required ShowSlug showSlug,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "GET",
      _uri('/s/shows/${Uri.encodeComponent(_wire(showSlug))}/members', query),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return ShowMemberCollection.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<void> updateShowMemberRole({
    required ShowSlug showSlug,
    required UserID userId,
    required UpdateShowMemberRole body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "PUT",
      _uri(
        '/s/shows/${Uri.encodeComponent(_wire(showSlug))}/members/${Uri.encodeComponent(_wire(userId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<void> removeShowMember({
    required ShowSlug showSlug,
    required UserID userId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "DELETE",
      _uri(
        '/s/shows/${Uri.encodeComponent(_wire(showSlug))}/members/${Uri.encodeComponent(_wire(userId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<SyncInventory> getSyncInventory({
    required ShowSlug showSlug,
    EpisodeID? cursor,
    EpisodePageLimit? limit,
  }) async {
    final query = <String, dynamic>{};
    if (cursor != null) query["cursor"] = _wire(cursor);
    if (limit != null) query["limit"] = _wire(limit);
    final request = http.Request(
      "GET",
      _uri('/s/shows/${Uri.encodeComponent(_wire(showSlug))}/sync', query),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return SyncInventory.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<CreatedPublicEpisodeDeletion> createSyncEpisodeDeletion({
    required ShowSlug showSlug,
    required EpisodeID episodeId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "POST",
      _uri(
        '/s/shows/${Uri.encodeComponent(_wire(showSlug))}/sync/episodes/${Uri.encodeComponent(_wire(episodeId))}/deletion',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{202}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return CreatedPublicEpisodeDeletion.fromJson(
      jsonDecode(utf8.decode(bytes)),
    );
  }

  Future<PendingTeamInvitation> createTeamInvitation({
    required CreateTeamInvitation body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request("POST", _uri('/s/team/invitations', query));
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return PendingTeamInvitation.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<PendingTeamInvitation> updateTeamInvitationRole({
    required TeamInvitationID invitationId,
    required UpdateTeamMemberRole body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "PUT",
      _uri(
        '/s/team/invitations/${Uri.encodeComponent(_wire(invitationId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return PendingTeamInvitation.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<void> revokeTeamInvitation({
    required TeamInvitationID invitationId,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "DELETE",
      _uri(
        '/s/team/invitations/${Uri.encodeComponent(_wire(invitationId))}',
        query,
      ),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<TeamMemberCollection> listTeamMembers() async {
    final query = <String, dynamic>{};
    final request = http.Request("GET", _uri('/s/team/members', query));
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return TeamMemberCollection.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<void> updateTeamMemberRole({
    required UserID userId,
    required UpdateTeamMemberRole body,
  }) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "PUT",
      _uri('/s/team/members/${Uri.encodeComponent(_wire(userId))}', query),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<void> removeTeamMember({required UserID userId}) async {
    final query = <String, dynamic>{};
    final request = http.Request(
      "DELETE",
      _uri('/s/team/members/${Uri.encodeComponent(_wire(userId))}', query),
    );
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<List<ClientTeam>> listClientTeams() async {
    final query = <String, dynamic>{};
    final request = http.Request("GET", _uri('/s/teams', query));
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return expectPublicList(jsonDecode(utf8.decode(bytes)))
        .map((item) => ClientTeam.fromJson(item))
        .toList();
  }

  Future<APIKeyWhoami> whoami() async {
    final query = <String, dynamic>{};
    final request = http.Request("GET", _uri('/s/whoami', query));
    request.headers['Accept'] = "application/json";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return APIKeyWhoami.fromJson(jsonDecode(utf8.decode(bytes)));
  }
}
